name: Test Python with pytest

on:
  workflow_dispatch:        # Permite ejecutar manualmente desde GitHub
  schedule:
    - cron: '0 6 * * *'      # Ejecutar todos los días a las 06:00 UTC
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Cambia a la versión que uses

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar tests con pytest
        run: pytest

